### ISSUE TITLE
distiller 0.3.4 (5?) roadmap

### ISSUE THREAD

**Issue by agalitsyna** [open2c/distiller-nf#182]
I included here only the issues that are either easy small fixes or structural changes that are important and also easy to introduce. 

- [ ] Support minimap2, bwa aln, bwa mem2 https://github.com/open2c/distiller-nf/issues/181
- [ ] Add short read alignment for reads <25 bp https://github.com/open2c/distiller-nf/issues/141 
- [ ] Add adaptor trimming https://github.com/open2c/distiller-nf/issues/146
- [ ] Fix sra-toolkit issue: https://github.com/open2c/distiller-nf/issues/157 
- [ ] Fix exhausted suffixes: https://github.com/open2c/distiller-nf/issues/169 
- [ ] Option to start from bam files: https://github.com/open2c/distiller-nf/issues/178

**Comment by Phlya** [comment]
We discussed adding filters to stats in distiller and @agalitsyna tried something, but in the end we never implemented it... Shall we do it? I propose to add the `--filter 'name"expression'` arguments to the dedup command, and also `--yaml` to actually store all the filter outputs?
